### ISSUE TITLE
102 - Job Request Remaining Tasks 

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/smart-inventory-management-system#102]
### TODO: 
- [ ] Complete the Controllers 
- [ ] Implement access control logic
- [ ] Implement Frontend Views 
- [ ] Write unit tests
   - [ ] Backend
   - [ ] Frontend
