### ISSUE TITLE
Equipment Handling

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/smart-inventory-management-system#25]
#### TODO List - Equipment
- [x] List Equipment
- [x] Create Equipment
- [x] Edit Equipment
- [x] Delete Equipment
- [x] Upload Thumbnails of Equipment
- [x] Implement Unit Tests

#### TODO List - Equipment Type
- [x] List Equipment Type
- [x] Create Equipment Type
- [x] Edit Equipment Type
- [x] Delete Equipment Type
- [x] Upload Thumbnails of Equipment Type
- [x] Implement Unit Tests

Implement Frontend Views 
- [x] Equipment Items
- [x] Equipment Supplies
