### ISSUE TITLE
Feature: Location Service

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/smart-inventory-management-system#95]
The objective of this is to define the locations of the items for the items entered into the inventory management system. (It can be a many-to-many relationship)

#### Items:
- Equipment (hand tools, power tools, ...)
- Components (DevBoards, Sensors, Modules, etc...)
- Raw Materials (Wood boards, ...)
- Machines (3D Printer, ...)
- Consumables (Resistors, Capacitors, ...)
- ...

#### TODO:
- [x] Identify the models
- [x] Design the database 
- [x] Plan routes 
- [x] Implement the models and controllers 
- [x] Design the views
- [x] Prepare seeders and factories 
- [x] Write unit testings

**Comment by ishanfdo18098** [comment]
![image](https://user-images.githubusercontent.com/73381996/174473217-27c5fb5d-07b5-4415-b970-6d48c6245126.png)
